### ISSUE TITLE
Templates do not use Parameters of the Template Chunk

### ISSUE THREAD

**Issue by zekrom-vale** [gadenbuie/epoxy#10]
Given the template `ci`:
```
    ```{glue ci, .open="(|", .close="|)", eval=FALSE}
    (|1+1|)
    ```
```

Having the following chunk pointing to the template is not enough:
```
    ```{glue n, ref.label="ci", data=dat}
    ```
```

It requires more parameters to work:
```
    ```{glue n, ref.label="ci", .open="(|", .close="|)", data=dat}
    ```
```

Might want to mention that or fix that.  It appears that this will apply to all other parameters used in the template.

**Comment by zekrom-vale** [comment]
The data argument is fine.

**Comment by gadenbuie** [comment]
The issue you're running into is part of how the `ref.label` knitr chunk option is designed. Using `ref.label` essentially copies the text _inside_ one code chunk to another, but it does not transfer the options. There are advantages and disadvantages to this (like the one you're running into here), but it's not something I'm inclined to address in epoxy.
