### ISSUE TITLE
LaTeX Preview

### ISSUE THREAD

**Issue by zekrom-vale** [gadenbuie/epoxy#11]
With RStudio 1.4 they introduced Visual Editor that allows LaTeX equations to be previewed, even if Visual Editor is off.  However, it breaks when the equation is written in code blocks, is there a way to fix this?  I don't know if this is even possible without modifying RStudio's code, so it might be a deep issue.

From this:
![image](https://user-images.githubusercontent.com/27376918/114076691-934b2f00-986c-11eb-85c5-1c39c915a6f7.png)

To something like this?
![image](https://user-images.githubusercontent.com/27376918/114076653-81698c00-986c-11eb-93be-e5ab93602ba0.png)

If you add back the ticks, the equation box stays there, but it *will not update*.  It would be great if this was fixed, even without replacement of the variables is fine by me as it is like code.  (`{`and `}` may mess up the LaTeX, so I used `(|` and `|)` so it would not mess it up.

**Comment by gadenbuie** [comment]
This is almost certainly an design choice of RStudio's and it's unlikely that LaTeX inside a glue chunk will ever show up in the visual preview.

By the way, have you seen the [`glue_latex` engine in epoxy](https://github.com/gadenbuie/epoxy#latex-blocks) for chunks that write raw LaTeX?
