### ISSUE TITLE
using both bold and collapse option inside .transformer

### ISSUE THREAD

**Issue by nithinmkp** [gadenbuie/epoxy#13]
I was wondering how can we use both (epoxy_style_collapse() and epoxy_style_bold() in the chunk.

i tried something like this

```{glue ,.transformer = list(epoxy_style_collapse(),epoxy_style_bold())}
 "The mean of {st1$Variable} is {round(st1$Mean,3)&}"
```

but this throws an error

**Comment by gadenbuie** [comment]
This is definitely something I want to do, I just need to figure out how 😝

**Comment by CorradoLanera** [comment]
For the API point-of-view, what about the following option?

    ```{glue, .transformer = c(epoxy_style_collapse(), epoxy_style_bold())}
    - The first three letters are {letters[1:3]*}.
    - When capitalized, they are {LETTERS[1:3]&}.
    - They're indexed by {1:3|}.
    ```

**Comment by nithinmkp** [comment]
Thats a nice suggestion. I had already tried that without parenthesis and did not work. And now epoxy is showing some error after I updated R and Rstudio. Hence am not able to try. Garrick, is there a conflict in epoxy after updation of R or Rstudio? 
![image](https://user-images.githubusercontent.com/65053643/123543038-61aa7b80-d76a-11eb-8322-924db0906bb4.png)

**Comment by gadenbuie** [comment]
> For the API point-of-view, what about the following option?

@CorradoLanera I like that style, but it's a little more tricky than it appears and the architecture of the epoxy transformers might be flawed enough that I'll have to rethink the whole setup. It's definitely something I want to support, though.

**Comment by gadenbuie** [comment]
> Garrick, is there a conflict in epoxy after updation of R or Rstudio?

@nithinmkp Unfortunately, you can't just click the green triangle, you have to knit the whole document to see the output of `glue` chunks.

**Comment by nithinmkp** [comment]
I tried with Kniting. Still it shows error.. [image: epoxy.png]





[image: Mailtrack]
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality5&>
Sender
notified by
Mailtrack
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality5&>
06/28/21,
09:40:41 PM
