### ISSUE TITLE
Emphasis tags not rendering in RStudio R chunk

### ISSUE THREAD

**Issue by mdmilgrom** [gadenbuie/epoxy#14]
Simple example using apreshill's bakeoff set:
````
```{r setup, include= FALSE}
library(bakeoff)
library(epoxy)
```
````

````
```{glue}
There are {nrow(bakeoff::series)} series of *The Great British Bake-Off* (or, **GBBO**).
```
````
The `nrow` correctly calculates, but the asterisks do not render italics or bold but just remain text, both inline in the code editor and in the Preview screen. I'm using the latest RStudio 4.1.0, glue 1.4.2, and epoxy 0.0.2.9000 on Mac OS.
<img width="920" alt="Screen Shot 2021-05-23 at 19 23 37" src="https://user-images.githubusercontent.com/4842633/119279887-6f656200-bbfc-11eb-9979-1bcdfb907e8f.png">

**Comment by gadenbuie** [comment]
This is expected, although not ideal. The output of a `glue` chunk is raw markdown, so RStudio shows the plain text of the markdown. When you knit the Rmd, however, the markdown will be rendered into the rich version of the final format (html, latex, word, etc.)

**Comment by mdmilgrom** [comment]
Probably naive question: What's the purpose of the "Preview" button in RStudio if not to render the markdown, or is it because it executes the `glue` chunk, outputting md, without knowledge of the necessity to render the output? This is an enhancement for RStudio itself then?

**Comment by gadenbuie** [comment]
So the `glue` chunk is effectively equivalent to an R chunk like this:

````
```{r results="asis"}
cat("There are", nrow(bakeoff::series), "series of *The Great British Bake-Off*.")
```
````

As far as I know, there's no way to tell knitr, rmarkdown or RStudio that the output of that particular line of code is _markdown_; instead everyone will just see it as plain text. So clicking the preview button previews the output of the chunk, which in this case is plain text.

When you render the R Markdown document, however, this plain text is interpreted by `pandoc` as markdown and converted into the final rich format. Note that that last step effectively happens outside of RStudio; `pandoc` is the command line utility that converts markdown to other formats.

I hope this was helpful; there are a lot of moving pieces in the pipeline and it is unfortunate that the preview isn't better in the RStudio IDE. I'll keep my eye out for a better solution for this.

**Comment by mdmilgrom** [comment]
That makes total sense and is in line with my second supposition, and I recognize the difficulty and tradeoff inherent to solutions created by pipelining these disparate building blocks together. I'm trying to think how one would solve this scalably, and it seems like without R/RStudio having anything like type annotation or a notion of input/output that any implementation would need to be specific for each library which generates markdown, or RStudio would need to call `pandoc` as part of the Preview action, which sounds like a performance drag for any remotely complicated document. It's an interesting problem.
