### ISSUE TITLE
epoxy_style_collapse in a dataframe

### ISSUE THREAD

**Issue by nithinmkp** [gadenbuie/epoxy#16]
I am trying to use glue chunk to write the results of a model which I put inside a tibble. I want to use epoxy_style collapse() along with this and the results are weird. Also, the superscript doesn't seem to work inside the glue chunk.

````
```{r models}
m1<-lm(mpg~1,data = mtcars)
m2<-lm(mpg~factor(cyl),data = mtcars)
mods<-list(m1=m1,m2=m2)
results<-tibble(modnum=c("mod1","mod2"),models=mods)
results <-results %>% mutate(
        diag=map(models,glance)
) %>% unnest(diag) %>% slice(1:2)
```
```{glue modelres, eval=FALSE,.transformer=epoxy_style_collapse()}
{modnum} has an R^2 of {r.squared&}
```
```{glue ref.label="modelres",data=results}
```
````

I want results like this
mod1 has an R^2 of 0 and mod2 has an R^2 of 0.7333.

**Comment by gadenbuie** [comment]
Thanks for the suggestion, but unfortunately I don't think epoxy will be able to support collapsing in this way.
