### ISSUE TITLE
Inline click choice input on shinyapps.io

### ISSUE THREAD

**Issue by gadenbuie** [gadenbuie/epoxy#7]
... I noticed that your app is hosted on shinyapp.io. I am using a similar approach in our shiny app. This works absolutely fine on local.
![working_epoxy](https://user-images.githubusercontent.com/8253658/86268757-a66ef700-bb96-11ea-8cc6-0572bfdcc73f.gif)

But as soon as I deploy it to shinyapps.io I see it like this
![notworking_epoxy](https://user-images.githubusercontent.com/8253658/86268775-acfd6e80-bb96-11ea-8a46-589db22ac610.gif)

_Originally posted by @senthilthyagarajan in https://github.com/gadenbuie/epoxy/pull/6#issuecomment-652522788_

**Comment by gadenbuie** [comment]
@senthilthyagarajan I moved this to an issue where we can better discuss this. Can you link to your shiny app or the code? Even better would be a [minimal reproducible example](https://reprex.tidyverse.org/).

**Comment by senthilthyagarajan** [comment]
Thank you @gadenbuie . Below is the code. I have the deployed app here https://mekanismbeta.shinyapps.io/epoxy/

`library(shiny)
# remotes::install_github("gadenbuie/epoxy@shiny-inline-inputs")
library(epoxy)

p5<- tibble::tribble(
  ~cost, ~clicks, ~impressions,   ~CPM,   ~CTR,
  26766.78,    6577,       204982, 130.58, 0.0321
)
# Module ------------------------------------------------------------------
epoxyModTestUI <- function(id) {
  ns <- NS(id)
  tagList(
    h2("Performace till Date"),
    epoxyHTML(
      .id = ns("demo"),
      .watch = list(click = "metric"),
      "<p>The total {{metric}}, ", 
      "so far in the campaign is {{metric_value}}.</p>"),
    
    tags$style(
      # not necessary, just looks cool
      '[data-epoxy-input-click]:hover { background-color: #fcf0cb; }'
    )
  )
}

epoxyModTest <- function(input, output, session, ...) {
  metric <- reactive({
    input$demo_metric_clicked
    sample(colnames(p5), 1)
  })
  
  output$demo <- renderEpoxyHTML(
    metric = metric(),
    metric_value = p5[metric()]
  )
}


# App ---------------------------------------------------------------------
ui <- fluidPage(
  epoxyModTestUI("test")
)

server <- function(input, output, session) {
  callModule(epoxyModTest, "test")
}

shinyApp(ui, server)`

**Comment by gadenbuie** [comment]
I'm pretty sure you just need to replace `p5[metric()]` with `p5[[metric()]]`

**Comment by senthilthyagarajan** [comment]
So how is it that is works on local but not when deployed. Thank you this worked. With this our summary has come down to one line as compared to 10 or more lines based on the data. This was very helpful

**Comment by gadenbuie** [comment]
No problem, thanks for sending a reprex! It might be related to there being different versions of `shiny` or `jsonlite`, I'm not exactly sure. I'll probably try to catch this case so that it doesn't trip up others.
