### ISSUE TITLE
Error when trying to use: In get_engine(options$engine) :   Unknown language engine 'glue' (must be registered via knit_engines$set())

### ISSUE THREAD

**Issue by dewoller** [gadenbuie/epoxy#8]
Great package, just scratched my exact itch.  I like the usage style (as a Rmd dialect), very clean. 

When trying to use epoxy, if knitr and/or rmarkdown libraries are not pre-loaded, you get the following error:

```
In get_engine(options$engine) :   
Unknown language engine 'glue' (must be registered via knit_engines$set())
```

Simple enough fix, but posting here for google-able posterity

**Comment by sfd99** [comment]
Hi **Dennis** 
and **Garrick** _(I follow you in Twitter, too!)_:

Trying to follow the 1st, simple ex in
     https://github.com/gadenbuie/epoxy 
in my "test.rmd" file:

---
title: "test"
author: "rw"
date: "2/18/2021"
output: html_document
---
library(epoxy)
```{glue}
The average speed of the cars was **{mean(cars$speed)} mph.**
But on average the distance travelled was only _{mean(cars$dist)}_.
```
But on [Knit],  the Rstudio output is:

test
rw
2/18/2021
library(epoxy)

The average speed of the cars was **{mean(cars$speed)} mph.**
But on average the distance travelled was only _{mean(cars$dist)}_.

Nothing gets rendered.

I must be missing 
something very  basic
...some specific R or Knitr commands?.
Just starting w/ Knitr,
so any specific baby-step instructions welcome!.

Help!
**SFd99
San Francisco
_Rstudio 1.4.1103
R 4.0.4
Ubuntu LINUX 20.04
knitr pkg 1.31
epoxy pkg 0.0.2.9000_
================**

**Comment by gadenbuie** [comment]
@sfd99 I think the piece that's missing is that the `library(epoxy)` needs to be within an `r` chunk so that it's executed, e.g.

````
```{r setup, include = FALSE}
library(epoxy)
```

```{glue}   
The average speed of the cars was **{mean(cars$speed)} mph.**
But on average the distance travelled was only _{mean(cars$dist)}_.
```
````

**Comment by sfd99** [comment]
**_Thanks, Garrick!._**
Worked through ALL examples, 
no problem.

**epoxy** is _truly_ powerful stuff...

Is there a chance to "weave" 
**epoxy** with **(g)awk** commands in an .RMD file?. 

**reason:**
I've been trying to use 
the **(g)awk** language engine in an .RMD file.
Too complicated!.

Maybe **epoxy** 
could come to the rescue by simplifying...

(Just an idea).
**SFd99
San Francisco
Rstudio 1.4.1103
R 4.0.4
Ubuntu LINUX 20.04
knitr pkg 1.31
epoxy pkg 0.0.2.9000
================**

**Comment by gadenbuie** [comment]
> When trying to use epoxy, if knitr and/or rmarkdown libraries are not pre-loaded, you get the following error:

@dewoller Do you happen to remember how you got into this state?
