### ISSUE TITLE
Include R chunks in Glue chunks?

### ISSUE THREAD

**Issue by zekrom-vale** [gadenbuie/epoxy#9]
Is there a way to include an R (or any other) chunk in the Glue chunk?  I have a class assignment that wants us to answer questions with different values.  In that, I need to include R code like this:
```r
  ```{glue, .open="{{", .close="}}"}
  $$\alpha={{alpha}}$$
  $$\frac\alpha2={{alpha/2}}$$
  \```{r}
  z=qnorm(alpha/2, lower.tail = FALSE)
  z
  \```
  $$z_{\frac\alpha2}\approx {{z}}$$
  #Unable to include ending of block
  ```
Now I could just split the block up, but then it won't work as a template.  Is the only way around it to format it by hand as a block?  I would love this feature!

**Comment by zekrom-vale** [comment]
Might have to parse the block more than once, as it relies on the output of glue.

**Comment by zekrom-vale** [comment]
I was able to add a simple code block, but it does not evaluate it as R code.

```r
    ```{r}
    alpha=.10
    blk="```"
    blkr="```{r}"
    ```
    
    ```{glue, .open="{{", .close="}}"}
    $$\alpha={{alpha}}$$
    $$\frac\alpha2={{alpha/2}}$$
    {{blkr}}
    z=qnorm(alpha/2, lower.tail = FALSE)
    z
    {{blk}}
    $$z_{\frac\alpha2}\approx $$
    ```
```

**Comment by zekrom-vale** [comment]
This will work for now.
```
    ```{r}
    alpha=.10
    blk="```"
    blkr="```{r}"
    ```
    
    ```{glue, .open="{{", .close="}}"}
    $$\alpha={{alpha}}$$
    $$\frac\alpha2={{alpha/2}}$$
    {{blkr}}
    qnorm(alpha/2, lower.tail = FALSE)
    {{blk}}
    $$z_{\frac\alpha2}\approx {{qnorm(alpha/2, lower.tail = FALSE)}}$$
    ```
```

**Comment by zekrom-vale** [comment]
Also, is it possible to call other glue templates inside a glue chunk?  So we can use templating like functions, calling other functions, reducing redundancy and error.

**Comment by gadenbuie** [comment]
> This will work for now.
> 
> ```
>     ```{r}
>     alpha=.10
>     blk="```"
>     blkr="```{r}"
>     ```
>     
> ```

Does this end up evaluating the `qnorm(alpha/2, lower.tail = FALSE)` line or just showing the code? I'd be surprised if it evaluates the R code. I don't think you can have nested knitr chunks. You can certainly include markdown (unevaluated) R code, and I would expect something like this to work:

`````markdown
```{r}
alpha=.10
```
    
````{glue, .open="{{", .close="}}"}
$$\alpha={{alpha}}$$

$$\frac\alpha2={{alpha/2}}$$

```r
qnorm(alpha/2, lower.tail = FALSE)
```

$$z_{\frac\alpha2}\approx {{qnorm(alpha/2, lower.tail = FALSE)}}$$
````
`````
